import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#060e20",
        "surface-container-low": "#131b2e",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
        "surface-container-highest": "#2d3449",
        "surface-dim": "#0b1326",
        "surface-bright": "#31394d",
        "surface-variant": "#2d3449",
        "surface-tint": "#b3c5ff",
        "surface": "#0b1326",
        "on-surface": "#dae2fd",
        "on-surface-variant": "#c2c6d8",
        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        "outline": "#8c90a1",
        "outline-variant": "#424656",
        "primary": "#b3c5ff",
        "on-primary": "#002b75",
        "primary-container": "#0066ff",
        "on-primary-container": "#f8f7ff",
        "inverse-primary": "#0054d6",
        "primary-fixed": "#dae1ff",
        "primary-fixed-dim": "#b3c5ff",
        "on-primary-fixed": "#001849",
        "on-primary-fixed-variant": "#003fa4",
        "secondary": "#ddfcff",
        "on-secondary": "#00363a",
        "secondary-container": "#00f1fe",
        "on-secondary-container": "#006a70",
        "secondary-fixed": "#74f5ff",
        "secondary-fixed-dim": "#00dbe7",
        "on-secondary-fixed": "#002022",
        "on-secondary-fixed-variant": "#004f54",
        "tertiary": "#c0c1ff",
        "on-tertiary": "#1000a9",
        "tertiary-container": "#5d60eb",
        "on-tertiary-container": "#faf6ff",
        "tertiary-fixed": "#e1e0ff",
        "tertiary-fixed-dim": "#c0c1ff",
        "on-tertiary-fixed": "#07006c",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "background": "#0b1326",
        "on-background": "#dae2fd",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "container-margin": "24px",
        gutter: "16px",
        unit: "4px",
        "section-gap": "48px",
      },
      fontFamily: {
        "display-lg": ["var(--font-geist)", "sans-serif"],
        "headline-lg": ["var(--font-geist)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-geist)", "sans-serif"],
        "headline-md": ["var(--font-geist)", "sans-serif"],
        "body-lg": ["var(--font-geist)", "sans-serif"],
        "body-md": ["var(--font-geist)", "sans-serif"],
        "label-md": ["var(--font-jetbrains)", "monospace"],
        "label-sm": ["var(--font-jetbrains)", "monospace"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
